### ISSUE TITLE
Upgrade compatibility to Expo SDK 51

### ISSUE THREAD

**Issue by lawnguyen** [luccasr73/with-rn-image-crop-picker#3]
Would really appreciate it, thanks for keeping this project alive.

**Comment by Arjit0762** [comment]
Yes, I too need it..

**Comment by luccasr73** [comment]
working on this now

**Comment by luccasr73** [comment]
@lawnguyen @Arjit0762 
on android appears to be ok, but i don't have an apple dev paid account, any of us can test `npm i @luccasr73/with-rn-image-crop-picker@0.1.5-alpha.0` on iOS?

**Comment by luccasr73** [comment]
and help in review of https://github.com/luccasr73/with-rn-image-crop-picker/pull/4/files

**Comment by luccasr73** [comment]
solved in #4

**Comment by Arjit0762** [comment]
Thanks Luccas for your support.. I will look into the integration..
